{% set name = "docformatter" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9dc71659d3b853c3018cd7b2ec34d5d054370128e12b79ee655498cb339cc711

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - docformatter = docformatter:main

requirements:
  host:
    - python >2
    - pip
    - poetry-core >=1.0.0
  run:
    - python >2
    - untokenize

test:
  commands:
    - docformatter -h

about:
  home: https://github.com/myint/docformatter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Formats docstrings to follow `PEP 257 <https://www.python.org/dev/peps/pep-0257/>`_.
  description: |
    docformatter currently automatically formats docstrings to follow a subset of the PEP 257 conventions. 
  dev_url: https://github.com/myint/docformatter

extra:
  recipe-maintainers:
    - carlodri
